<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="foot w_auto">
	<a href="/about/">公司简介</a> | <a href="/advertising/">广告服务</a> | <a href="/contact/">联系我们</a> | <a href="/hr/">诚聘英才</a> | <a href="/index.php?m=article&c=sitemap">网站地图</a> | 意见反馈 <br>
	Copyright &copy; 2010-2011 Corporation, All Rights Reserved Powered by <a href="http://www.zcms.cc" target="_blank">Zcms</a>
</div>