<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="footer">
	<div class="footpage">
		<ul>
			<li><a href="/" title="关于我们">关于我们</a></li>
			<li><a href="/" title="友情链接">广告服务</a></li>
			<li><a href="/" title="联系我们">联系我们</a></li>
			<li><a href="/" title="诚聘英才">诚聘英才</a></li>
            <li><a href="/" title="网站地图">网站地图</a></li>
        </ul>
	 </div>
       Powered by <a href="http://www.zcms.cc" title="ZCMS内容管理系统,简单而强大" target="_blank"><strong>Zcms</strong></a> Themes Design By  <a href="<?php echo $weburl; ?>" target="_blank"><?php echo $webname; ?></a> Inc.<br /><?php echo $powerby; ?>&nbsp;&nbsp;<?php echo $benan; ?> &nbsp;&nbsp;

    	   <div class="clear"></div>
    	 </div>
    <!-- Footer end -->
    	 <div class="clear"></div>
   </div>